### hello
GET http://localhost:8090/kotlin-demo/hello
Accept: application/json

### sayHello
GET http://localhost:8090/kotlin-demo/sayHello?name=winterfell
Accept: application/json

### sayHelloByUser
POST http://localhost:8090/kotlin-demo/sayHelloByUser
Content-Type: application/json
Accept: application/json

{
  "name": "zhuzhenjie"
}

### sayHelloByUser
POST http://localhost:8090/kotlin-demo/sayHelloByUser
Content-Type: application/json
Accept: application/json

{
  "id": 1021111,
  "name": "zhenjiezhu",
  "grade": 96.5
}


### sayHelloByUser
POST http://localhost:8090/kotlin-demo/copyUser
Content-Type: application/json
Accept: application/json

{
  "id": 1021111,
  "name": "zhenjiezhu",
  "grade": 96.5
}

### sayHelloByUser
POST http://localhost:8090/kotlin-demo/copyUser
Content-Type: application/json
Accept: application/json

{
  "id": 123,
  "grade": 96.5
}

### 测试 HttpServletRequest
GET http://localhost:8090/kotlin-demo/testHttpServletRequest
Accept: application/json

### curl 测试

### 获取学生列表
GET http://localhost:8090/kotlin-demo/student/list
Accept: application/json

### 获取学生列表
GET http://localhost:8090/kotlin-demo/student-copy/list
Accept: application/json

### 获取学生列表2
GET http://localhost:8090/kotlin-demo/student/list2
Accept: application/json

### 分页查询学生列表
POST http://localhost:8090/kotlin-demo/student/pageList
Content-Type: application/json
Accept: application/json

{
  "current": 1,
  "size": 5
}


### 根据 id 获取学生
GET http://localhost:8090/kotlin-demo/student/getById?id=1
Accept: application/json

### 根据 id 获取 StudentCopy
GET http://localhost:8090/kotlin-demo/student-copy/getById?id=2
Accept: application/json

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{
  "name": "hello"
}

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{
  "name": "IntelliJ"
}

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{}

### 添加学生
POST http://localhost:8090/kotlin-demo/student/add
Content-Type: application/json
Accept: application/json

{
  "name": "{{$uuid}}"
}

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{
  "name": "hello"
}

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{
  "name": "IntelliJ"
}

### 根据 name 获取学生
POST http://localhost:8090/kotlin-demo/student/getByName
Content-Type: application/json
Accept: application/json

{}

### 添加学生
POST http://localhost:8090/kotlin-demo/student/add
Content-Type: application/json
Accept: application/json

{
  "name": "{{$uuid}}"
}