### hello
GET http://127.0.0.1:8080/kotlin-examples/hello
Accept: application/json

### say hello
GET http://127.0.0.1:8080/kotlin-examples/sayHello?name=Ray
Accept: application/json

### testHttpServletRequest
GET http://127.0.0.1:8080/kotlin-examples/testHttpServletRequest
Accept: application/json

### say hello by user
POST http://127.0.0.1:8080/kotlin-examples/sayHelloByUser
Accept: application/json
Content-Type: application/json

{
  "name": "Rain"
}

### copy user
POST http://127.0.0.1:8080/kotlin-examples/copyUser
Accept: application/json
Content-Type: application/json

{
}


