### hello
GET {{root_uri}}/kotlin-examples/hello
Accept: application/json

### say hello
GET {{root_uri}}/kotlin-examples/sayHello?name=Ray
Accept: application/json

### testHttpServletRequest
GET {{root_uri}}/kotlin-examples/testHttpServletRequest
Accept: application/json

### say hello by user
POST {{root_uri}}/kotlin-examples/sayHelloByUser
Accept: application/json
Content-Type: application/json

{
  "name": "Rain"
}

### copy user
POST {{root_uri}}/kotlin-examples/copyUser
Accept: application/json
Content-Type: application/json

{
}


