### 测试默认topic
POST {{root_uri}}/mqtt/publishToDefaultTopic
Accept: application/json
Content-Type: application/json

{
  "msg": "hello world"
}

### withoutqos
POST {{root_uri}}/mqtt/publishWithoutQos
Accept: application/json
Content-Type: application/json

{
  "topic": "/hello/world",
  "msg": "hello world"
}

### withqos
POST {{root_uri}}/mqtt/publishWithQos
Accept: application/json
Content-Type: application/json

{
  "topic": "/hello/world",
  "qos": 2,
  "msg": "hello world"
}



