### 获取所有包含父母信息的学生列表
POST {{root_uri}}/curd-examples/student-with-parent/list-all
Accept: application/json
Content-Type: application/json

### 获取指定id为1的包含父母信息的学生
POST {{root_uri}}/curd-examples/student-with-parent/list-all-by-condition
Accept: application/json
Content-Type: application/json

### 分页获取所有包含父母信息的学生列表
POST {{root_uri}}/curd-examples/student-with-parent/page-list
Accept: application/json
Content-Type: application/json

{
  "current": 1,
  "size": 1
}

### 获取指定id为1的包含父母信息的学生
POST {{root_uri}}/curd-examples/student-with-parent/get-by-id
Accept: application/json
Content-Type: application/json

{
  "id": 1
}

### 获取所有包含经纬度的学生列表
POST {{root_uri}}/curd-examples/student-with-address/list-all
Accept: application/json
Content-Type: application/json


### 分页获取所有包含经纬度的学生列表
POST {{root_uri}}/curd-examples/student-with-address/page-list
Accept: application/json
Content-Type: application/json

{
  "current": 2,
  "size": 1
}

### Student With Address --> get by id

